site_name: Kleber Yokota
site_url: https://example.com

theme:
  language: en
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Dark mode
      primary: indigo
      accent: amber
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Light mode
      primary: blue grey
      accent: deep orange
  font:
    text: Gentium Plus
    code: Exo 2
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - toc.integrate

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
plugins:
  - search
  - blog:
      authors_profiles: true
      blog_toc: true
      blog_dir: blog
#      archive_date_format: yyyy-MM
#      archive_url_format: yyyy-MM
      post_date_format: medium
      categories_allowed:
        - Personal
        - Infrastructure
        - Data

  - tags:
      tags_file: tags.md

copyright: Copyright &copy; 2025 Kleber Yokota
